### ISSUE TITLE
[Low Prio - iOS wallet] Cannot share non-DCC PDF

### ISSUE THREAD

**Issue by michawol** [eu-digital-green-certificates/dgca-wallet-app-ios#134]
## Describe the bug
when i want to share a non-DCC PDF, there is no "Share"-Button visible

## Expected behaviour
a non-DCC PDF is saved. when the pdf is viewd in walletApp, the must be a "Share"-Button
to share the pdf

## Steps to reproduce the issue

1. save non-dcc in walletApp
2. open the saved pdf

## Technical details
iPhone 7, IOS 15.3.1
WalletApp 1.3.1 (5)
[testform1.pdf](https://github.com/eu-digital-green-certificates/dgca-wallet-app-ios/files/8224576/testform1.pdf)

**Comment by RalicaY** [comment]
On my end the share button is not missing but it is largely covered by the pdf document, so that no text "share" is seen.  Yet the button exists and when I press in the lower part of the pdf-Document approximately above the covered button, the share-fubctionality is available and working.  My Device is: : iPhone 8 plus v. Lutz, iOS 15.3.1. Wallet App 1.3.1 (5)

**Comment by michawol** [comment]
i agree. the button is not visible, but when i click at the lower part, the share-menu is available.

**Comment by PaulBallmann** [comment]
Addressed in 1.3.2 (2).

**Comment by RalicaY** [comment]
On my device the button is visible, so successfully tested and I close the ticket, iPhone 8 plus v. Lutz, iOS 15.3.1. Wallet App 1.3.2 (2)
