### ISSUE TITLE
iOS - No rules will be used for check validity

### ISSUE THREAD

**Issue by rebwalz** [eu-digital-green-certificates/dgca-wallet-app-ios#85]
## Describe the bug

on choosing a certificate to check the validity, the choosen country has no rules. Even if I know that the country should have rules.

## Expected behaviour
the choosen certificate should be checked by choosen date and country.

## Steps to reproduce the issue

1. Open WalletApp
2. choose a already saved certificate
3. push the button: "check Validity"
4. choose a country with businessRules
5. Choose a date
6. push "I Agree, check validity
7. see the message: "Sorry! no rules for this country"

## Technical details

- Host Machine OS (Windows/Linux/Mac):
IPhone Xs
Modellnummer: MT9G2ZD/A
IOS-Version: 14.6 (18F72)
ENF-Version:
WalletApp Version  1.1.0

**Comment by kerstin-oppermann-tsi** [comment]
@rebwalz seems that this issue exits only for valid certificates? Or do you have an invalid one that doesnt match? Then please provide the country selection and/or screen shots, so that @alexchornyi can reproduce this and fix.

i claimed a vac cert (with 1 vac of 2) and checked it against germany and then I got the rule check for the new cert and also for the claimed cert when I check it again.
![image](https://user-images.githubusercontent.com/81565834/125257577-d8647e80-e2fd-11eb-9c3e-b160632d0be5.png)
![image](https://user-images.githubusercontent.com/81565834/125257685-f3cf8980-e2fd-11eb-988f-baaa6e801888.png)

**Comment by rebwalz** [comment]
![image](https://user-images.githubusercontent.com/81565021/125262682-aa356d80-e302-11eb-828e-e78b745c1008.png)
![image](https://user-images.githubusercontent.com/81565021/125263032-f84a7100-e302-11eb-930b-0a036648e9d8.png)
![image](https://user-images.githubusercontent.com/81565021/125263086-05676000-e303-11eb-926f-d77025dd260b.png)
![image](https://user-images.githubusercontent.com/81565021/125262900-d94bdf00-e302-11eb-8004-e94b1e444e62.png)
![image](https://user-images.githubusercontent.com/81565021/125262944-e668ce00-e302-11eb-8efe-1327f4cb7fda.png)

**Comment by rebwalz** [comment]
But the rukles seems not be checked correct. The Testresult was at 02.06.2021. But the rule was set as passed for germany at the 14.07.2021:
![image](https://user-images.githubusercontent.com/81565021/125263677-832b6b80-e303-11eb-9e5f-2aa486d4406a.png)

**Comment by alexchornyi** [comment]
@rebwalz Please recheck #94 in new version

**Comment by kerstin-oppermann-tsi** [comment]
I checked the related issue https://github.com/eu-digital-green-certificates/dgca-wallet-app-ios/issues/89. This is fixed now with the new wallet app version 1.1.0.1(5). 

@rebwalz Please retest this ticket with the new fix.

**Comment by RalicaY** [comment]
Successfully tested with iOS Wallet App 1.1.0 (7) tst
