### ISSUE TITLE
iOS - Who should issue the TAN code?

### ISSUE THREAD

**Issue by red-lonely-neuron** [eu-digital-green-certificates/dgca-wallet-app-ios#92]
**Who should issue the TAN code?**

When I try to enrol a new QR code of a green certificate with the dgca-wallet-app-ios application, I am asked for a TAN code. First I have tried my own green certificate then I have attempted to enrol the ones at https://dgc.a-sit.at/ehn/testsuite . The issuer of my green certificate hasn't sent me a TAN code. The test certificates at dgc.a-sit.at don't have an accompanying TAN code either.

The document at https://ec.europa.eu/health/sites/default/files/ehealth/docs/digital-green-certificates_v4_en.pdf, chapter 5.1, says it's the issuer duty to produce such a code.

What am I missing?

Best regards,
Alex.

**Comment by mkubicek-dtc** [comment]
Hi Alex

The TAN is issued by the dgca-issuance-service. By design you can't import other DCCs without further modifications of the code.

The repositories in eu-digital-green-certificates contain an application ecosystem that may be used by countries connected to the DCC gateway. Please find more information here: https://github.com/eu-digital-green-certificates/dgc-overview

For questions regarding Wallet availability in your yountry please contact the national health authority.

Kind regards
Milan
T-Systems DCC PMO
